variables:
  IMAGE_OPENJDK_MVN: maven:3.8.3-openjdk-17
  IMAGE_NODE_LATEST: node:latest
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true
  DOCS_FOLDER: "pri-application"
  SPEC_TO_DISPLAY: "pri-api.yaml"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
