openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080/pri
  description: Generated server url
paths:
  /project/:
    get:
      tags:
      - project-controller
      operationId: getProjects
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectCreationRequestDTO'
    post:
      tags:
      - project-controller
      operationId: createProject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectCreationRequestDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectCreationResponseDTO'
  /externallink/single:
    post:
      tags:
      - external-link-controller
      operationId: createExternalLink
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalLinkCreationRequestDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExternalLinkCreationRequestDTO'
  /externallink/:
    post:
      tags:
      - external-link-controller
      operationId: createExternalLinks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ExternalLinkCreationRequestDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExternalLinkCreationRequestDTO'
  /data/supervisors:
    post:
      tags:
      - data-feed-controller
      operationId: createSupervisor
      parameters:
      - name: studyYear
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - data
              type: object
              properties:
                data:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
  /data/students:
    post:
      tags:
      - data-feed-controller
      operationId: createStudents
      parameters:
      - name: studyYear
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - data
              type: object
              properties:
                data:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
  /user/supervisor:
    get:
      tags:
      - user-controller
      operationId: getSupervisors
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupervisorDTO'
  /user/student:
    get:
      tags:
      - user-controller
      operationId: getStudents
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudentDTO'
components:
  schemas:
    ProjectCreationRequestDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        technologies:
          uniqueItems: true
          type: array
          items:
            type: string
        acceptanceStatus:
          type: string
          enum:
          - PENDING
          - CONFIRMED
          - ACCEPTED
        supervisorId:
          type: integer
          format: int64
        studyYear:
          type: string
    ProjectCreationResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        technologies:
          uniqueItems: true
          type: array
          items:
            type: string
        acceptanceStatus:
          type: string
          enum:
          - PENDING
          - CONFIRMED
          - ACCEPTED
        supervisor:
          $ref: '#/components/schemas/SupervisorDTO'
        studyYear:
          $ref: '#/components/schemas/StudyYearDTO'
    StudyYearDTO:
      type: object
      properties:
        studyYear:
          type: string
    SupervisorDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userData:
          $ref: '#/components/schemas/UserDataDTO'
    UserDataDTO:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
    ExternalLinkCreationRequestDTO:
      type: object
      properties:
        externalLinkDefinitionId:
          type: integer
          format: int64
        projectId:
          type: integer
          format: int64
        link:
          type: string
    StudentDTO:
      type: object
      properties:
        userData:
          $ref: '#/components/schemas/UserDataDTO'
