openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080/pri
  description: Generated server url
paths:
  /project/:
    get:
      tags:
      - project-controller
      operationId: getProjects
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDTO'
    post:
      tags:
      - project-controller
      operationId: createProject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectDTO'
  /data/supervisors:
    post:
      tags:
      - data-feed-controller
      operationId: createSupervisor
      parameters:
      - name: studyYear
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - data
              type: object
              properties:
                data:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
  /data/students:
    post:
      tags:
      - data-feed-controller
      operationId: createStudents
      parameters:
      - name: studyYear
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - data
              type: object
              properties:
                data:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
components:
  schemas:
    ProjectDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        projectName:
          type: string
