openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080/pri
  description: Generated server url
paths:
  /project/{projectId}/external-link:
    get:
      tags:
      - project-controller
      operationId: getExternalLinkDataByProjectId
      parameters:
      - name: projectId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExternalLinkDataDTO'
    put:
      tags:
      - project-controller
      operationId: updateExternalLinkData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalLinkDataDTO'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExternalLinkDataDTO'
  /project:
    get:
      tags:
      - project-controller
      operationId: getProjects
      parameters:
      - name: study-year
        in: header
        required: true
        schema:
          type: string
      - name: user-index-number
        in: header
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDTO'
    post:
      tags:
      - project-controller
      operationId: createProject
      parameters:
      - name: study-year
        in: header
        required: true
        schema:
          type: string
      - name: user-index-number
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDetailsDTO'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectDetailsDTO'
  /project/external-link:
    get:
      tags:
      - project-controller
      operationId: getExternalLinkData
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExternalLinkDataDTO'
    post:
      tags:
      - project-controller
      operationId: createExternalLinkData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalLinkDataDTO'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExternalLinkDataDTO'
  /data/import/supervisor:
    post:
      tags:
      - data-feed-controller
      operationId: createSupervisors
      parameters:
      - name: study-year
        in: header
        required: true
        schema:
          type: string
      - name: user-index-number
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - data
              type: object
              properties:
                data:
                  type: string
                  format: binary
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
  /data/import/student:
    post:
      tags:
      - data-feed-controller
      operationId: createStudents
      parameters:
      - name: study-year
        in: header
        required: true
        schema:
          type: string
      - name: user-index-number
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - data
              type: object
              properties:
                data:
                  type: string
                  format: binary
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
  /user/supervisor:
    get:
      tags:
      - user-controller
      operationId: getSupervisors
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupervisorDTO'
  /user/student:
    get:
      tags:
      - user-controller
      operationId: getStudents
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudentDTO'
  /project/{id}:
    get:
      tags:
      - project-controller
      operationId: getProjectById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectDetailsDTO'
  /data/export/student:
    get:
      tags:
      - data-feed-controller
      operationId: exportStudentsData
      parameters:
      - name: study-year
        in: header
        required: true
        schema:
          type: string
      - name: user-index-number
        in: header
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        "200":
          description: OK
components:
  schemas:
    ErrorInfo:
      type: object
      properties:
        date:
          type: string
          format: date-time
        httpStatusNumber:
          type: integer
          format: int32
        errorMessage:
          type: string
    ExternalLinkDTO:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
        externalLinkDefinition:
          $ref: '#/components/schemas/ExternalLinkDefinitionDTO'
    ExternalLinkDataDTO:
      required:
      - externalLinks
      - projectId
      type: object
      properties:
        projectId:
          type: integer
          format: int64
        projectName:
          type: string
        supervisor:
          $ref: '#/components/schemas/SupervisorDTO'
        externalLinks:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ExternalLinkDTO'
    ExternalLinkDefinitionDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        columnHeader:
          type: string
        deadline:
          type: string
          format: date
    SupervisorDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userData:
          $ref: '#/components/schemas/UserDataDTO'
    UserDataDTO:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
    ProjectDetailsDTO:
      required:
      - description
      - name
      - students
      - supervisor
      - technologies
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        technologies:
          uniqueItems: true
          type: array
          items:
            type: string
        accepted:
          type: boolean
        supervisor:
          $ref: '#/components/schemas/SupervisorDTO'
        students:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/StudentDTO'
        admin:
          type: string
        externalLinks:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ExternalLinkDTO'
    StudentDTO:
      type: object
      properties:
        indexNumber:
          type: string
        role:
          type: string
          enum:
          - FRONTEND
          - BACKEND
          - FULLSTACK
        name:
          type: string
        email:
          type: string
    ProjectDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        supervisor:
          $ref: '#/components/schemas/SupervisorDTO'
        accepted:
          type: boolean
